-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE negozio.fornitore
(
    codice_fornitore bigint NOT NULL,
    nome character varying NOT NULL,
    indirizzo character varying NOT NULL,
    citta character varying NOT NULL,
    PRIMARY KEY (codice_fornitore)
);

CREATE TABLE negozio.prodotto
(
    codice_prodotto bigint NOT NULL,
    nome character varying NOT NULL,
    descrizione character varying NOT NULL,
    marca character varying NOT NULL,
    prezzo double precision NOT NULL,
    fk_fornitore bigint NOT NULL,
    PRIMARY KEY (codice_prodotto)
);

ALTER TABLE negozio.prodotto
    ADD FOREIGN KEY (fk_fornitore)
    REFERENCES negozio.fornitore (codice_fornitore)
    NOT VALID;

END;